name: Python application

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest  # poprawka z 'runs -on' na 'runs-on'
    strategy:
      matrix:
        python-version: ["3.11", "3.12"]  # poprawka z 'python - version'

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3  # poprawka z 'setup - python'
      with:
        python-version: ${{ matrix.python-version }}  # dynamiczna wersja z macierzy

    - name: Test with Pytest
      run: |
        pytest

    - name: Lint with Pylint
      run: |
        pylint D:/Pulpit/PWR/Praaktyka_programowania/CI-CD/utils.py  # OK, ale lepiej uogólnić

    - name: Format with Black
      run: |
        black --check .
